version: "3.4"

services:
  sut:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: builder
    image: debos-builder
    working_dir: /usr/local/go/src/github.com/davidmhewitt/debos
    command: go test -v ./...
